okta/okta-spring-boot

- oauth2/src/main/java/com/okta/spring/oauth/OktaPropertiesMappingEnvironmentPostProcessor.java
- oauth2/src/main/java/com/okta/spring/oauth/implicit/ResourceServerConfig.java
- okta-spring-boot-starter/pom.xml
Cleaned up pom dependencies (they all come from oauth2 atm)
Added alias for okta.oauth2.audience -> security.oauth2.resoruce.serviceId
> Rename the resourceServerConfigurerAdapter bean to oktaResourceServerConfigurerAdapter as to not conflict with other beans

- config/pom.xml
- config/src/main/java/com/okta/spring/config/OktaClientProperties.java
- coverage/pom.xml
- examples/hosted-login-code-flow/pom.xml
- examples/pom.xml
- examples/redirect-code-flow/pom.xml
- examples/siw-jquery/pom.xml
- integration-tests/oauth2/pom.xml
- oauth2/src/main/java/com/okta/spring/oauth/OktaPropertiesMappingEnvironmentPostProcessor.java
- okta-spring-boot-starter/pom.xml
- pom.xml
- sdk/pom.xml
- sdk/src/main/java/com/okta/spring/sdk/OktaSdkConfig.java
- sdk/src/main/java/com/okta/spring/sdk/cache/SpringCache.java
- sdk/src/main/java/com/okta/spring/sdk/cache/SpringCacheManager.java
- sdk/src/main/resources/META-INF/spring.factories
- sdk/src/test/groovy/com/okta/spring/sdk/MockSdkApp.groovy
- sdk/src/test/groovy/com/okta/spring/sdk/MockSdkAppWithCache.groovy
- sdk/src/test/groovy/com/okta/spring/sdk/OktaSdkConfigTest.groovy
- sdk/src/test/groovy/com/okta/spring/sdk/OktaSdkConfigWithCacheTest.groovy
- sdk/src/test/groovy/com/okta/spring/sdk/OktaSdkConfigWithProxyTest.groovy
- sdk/src/test/groovy/com/okta/spring/sdk/cache/SpringCacheManagerTest.groovy
- sdk/src/test/groovy/com/okta/spring/sdk/cache/SpringCacheTest.groovy
bump version to 0.3.0 to reflect this
> Allow Injection the Okta SDK client

- config/pom.xml
- coverage/pom.xml
- examples/hosted-login-code-flow/pom.xml
- examples/pom.xml
- examples/redirect-code-flow/pom.xml
- examples/siw-jquery/pom.xml
- integration-tests/oauth2/pom.xml
- integration-tests/oauth2/src/main/java/com/okta/spring/tests/oauth2/implicit/BasicImplicitFlowApplication.java
- integration-tests/oauth2/src/test/resources/testRunner.yml
- oauth2/pom.xml
- okta-spring-boot-starter/pom.xml
- pom.xml
- sdk/pom.xml
The example app needed to change to support this (this was back ported from the okta spring samples repo)
> Update the oidc-tck to 0.2.2

- integration-tests/oauth2/pom.xml
- integration-tests/oauth2/src/test/groovy/com/okta/spring/tests/oauth2/implicit/ImplicitRemoteValidationGroupIT.groovy
- integration-tests/oauth2/src/test/resources/versions.properties
- oauth2/pom.xml
- oauth2/src/main/java/com/okta/spring/oauth/discovery/OidcDiscoveryClient.java
- oauth2/src/main/java/com/okta/spring/oauth/http/UserAgent.java
- oauth2/src/main/java/com/okta/spring/oauth/http/Version.java
- oauth2/src/main/resources/com/okta/spring/version.properties
- okta-spring-boot-starter/pom.xml
- okta-spring-boot-starter/src/test/groovy/com/okta/spring/oauth/http/UserAgentTest.groovy
- okta-spring-boot-starter/src/test/resources/versions.properties
- Adds tests for User-Agent
- Bumps SDK version to 1.0.0
- Bumps tck version to 0.2.2
> Add's User-Agent header to discovery request

- config/pom.xml
- coverage/pom.xml
- examples/hosted-login-code-flow/pom.xml
- examples/pom.xml
- examples/redirect-code-flow/pom.xml
- examples/siw-jquery/pom.xml
- integration-tests/oauth2-boot2/pom.xml
- integration-tests/oauth2-boot2/src/main/java/com/okta/spring/tests/oauth2/code/BasicRedirectCodeFlowApplication.java
- integration-tests/oauth2-boot2/src/main/java/com/okta/spring/tests/oauth2/implicit/BasicImplicitFlowApplication.java
- integration-tests/oauth2-boot2/src/main/resources/application.yml
- integration-tests/oauth2-boot2/src/test/groovy/com/okta/spring/tests/oauth2/SpringApplicationUnderTest.groovy
- integration-tests/oauth2-boot2/src/test/groovy/com/okta/spring/tests/oauth2/implicit/ImplicitLocalValidationGroupIT.groovy
- integration-tests/oauth2-boot2/src/test/groovy/com/okta/spring/tests/oauth2/implicit/ImplicitRemoteValidationGroupIT.groovy
- integration-tests/oauth2-boot2/src/test/resources/testRunner.yml
- integration-tests/oauth2-boot2/src/test/resources/versions.properties
- integration-tests/oauth2/pom.xml
- oauth2/pom.xml
- oauth2/src/main/java/com/okta/spring/oauth/OktaPropertiesMappingEnvironmentPostProcessor.java
- oauth2/src/main/java/com/okta/spring/oauth/code/OktaOAuthCodeFlowConfiguration.java
- okta-spring-boot-starter/pom.xml
- pom.xml
- sdk/pom.xml
- sdk/src/main/java/com/okta/spring/sdk/OktaSdkConfig.java
Based on the work of #43, but supports both Spring Boot 1 and 2
Fixes: #43
> Add support for Spring Boot 2.0

- README.md
removes the duplicate effort (and forgetting to update the README)
> Releases are now ONLY recorded as github releases

- integration-tests/oauth2-boot2/pom.xml
- okta-spring-boot-starter/pom.xml
- src/owasp/owasp-suppression.xml
Exclude false positive from owasp dep scan
> Cleanup duplicate spring version declaration

- config/pom.xml
- coverage/pom.xml
- examples/hosted-login-code-flow/pom.xml
- examples/pom.xml
- examples/redirect-code-flow/pom.xml
- examples/siw-jquery/pom.xml
- integration-tests/oauth2-boot2/pom.xml
- integration-tests/oauth2/pom.xml
- oauth2/pom.xml
- okta-spring-boot-starter/pom.xml
- pom.xml
- sdk/pom.xml
Automated with: `mvn versions:set -DnewVersion=0.6.0-SNAPSHOT`
> Updating project version to 0.6.0

- README.md
> Tweak SDK injection in Readme

- README.md
- examples/hosted-login-code-flow/src/main/resources/templates/okta/login.html
> Update doc strings from `{yourOktaDomain}.com` to `{yourOktaDomain}`

- integration-tests/oauth2-boot2/pom.xml
- integration-tests/oauth2/pom.xml
- pom.xml
- src/ci/release.sh
Fixes dependency scope of IT projects
Remove dependencies that are no longer directly used (moved to the tck project)
Update to tck and config-check released versions
correct broken link in release.sh
> Minor pom cleanup

- sdk/pom.xml
The test lib mockito don't have the expected scope.
> Fix test dependency scope

- coverage/pom.xml
- examples/config-server/pom.xml
- examples/hosted-login-code-flow/pom.xml
- examples/pom.xml
- examples/redirect-code-flow/pom.xml
- examples/siw-jquery/pom.xml
- examples/webflux-resource-server/pom.xml
- integration-tests/oauth2-reactive/pom.xml
- integration-tests/oauth2/pom.xml
- oauth2/pom.xml
- okta-spring-boot-starter/pom.xml
- pom.xml
- sdk/pom.xml
Automated version update from the maven versions plugin
> Updated project version to 1.1.0

- pom.xml
- src/owasp/owasp-suppression.xml
A few Netty related artifacts have get detected as the wrong cpe
> Update jackson dependency and remove owasp check false positive

- integration-tests/oauth2-reactive/src/main/java/com/okta/spring/tests/oauth2/reactive/implicit/ReactiveImplicitFlowApplication.java
- integration-tests/oauth2-reactive/src/test/groovy/com/okta/spring/tests/oauth2/implicit/ReactiveImplicitLocalValidationGroupIT.groovy
- integration-tests/oauth2/src/main/java/com/okta/spring/tests/oauth2/implicit/BasicImplicitFlowApplication.java
- integration-tests/oauth2/src/test/groovy/com/okta/spring/tests/oauth2/implicit/ImplicitLocalValidationGroupIT.groovy
- oauth2/pom.xml
- oauth2/src/main/java/com/okta/spring/boot/oauth/BrowserFriendlyBearerTokenServerAuthenticationEntryPoint.java
- oauth2/src/main/java/com/okta/spring/boot/oauth/ConditionalOnOktaClientProperties.java
- oauth2/src/main/java/com/okta/spring/boot/oauth/ConditionalOnOktaResourceServerProperties.java
- oauth2/src/main/java/com/okta/spring/boot/oauth/Okta.java
- oauth2/src/main/java/com/okta/spring/boot/oauth/OktaOAuth2AutoConfig.java
- oauth2/src/main/java/com/okta/spring/boot/oauth/OktaOAuth2Configurer.java
- oauth2/src/main/java/com/okta/spring/boot/oauth/OktaOAuth2ResourceServerAutoConfig.java
- oauth2/src/main/java/com/okta/spring/boot/oauth/ReactiveOktaOAuth2AutoConfig.java
- oauth2/src/main/java/com/okta/spring/boot/oauth/ReactiveOktaOAuth2ResourceServerAutoConfig.java
- oauth2/src/main/java/com/okta/spring/boot/oauth/ReactiveOktaOAuth2ResourceServerHttpServerAutoConfig.java
- oauth2/src/main/java/com/okta/spring/boot/oauth/ReactiveOktaOAuth2ServerHttpServerAutoConfig.java
- oauth2/src/main/java/com/okta/spring/boot/oauth/env/OktaOAuth2PropertiesMappingEnvironmentPostProcessor.java
- oauth2/src/main/java/com/okta/spring/boot/oauth/env/RemappedPropertySource.java
- oauth2/src/test/groovy/com/okta/spring/boot/oauth/AutoConfigConditionalTest.groovy
> Adds a check for required properties before configuring OAuth flows

- README.md
Just a small change to the README.md for some of the example Java code
> Fix the 'Create a minimal Spring Boot application' example Java code

- coverage/pom.xml
- examples/config-server/pom.xml
- examples/hosted-login-code-flow/pom.xml
- examples/pom.xml
- examples/redirect-code-flow/pom.xml
- examples/siw-jquery/pom.xml
- examples/webflux-resource-server/pom.xml
- integration-tests/oauth2-reactive/pom.xml
- integration-tests/oauth2/pom.xml
- oauth2/pom.xml
- okta-spring-boot-starter/pom.xml
- pom.xml
- sdk/pom.xml
via `mvn versions:set -DnewVersion=1.2.0-SNAPSHOT`
> Updated to version 1.2.0-SNAPSHOT

- oauth2/src/main/java/com/okta/spring/boot/oauth/OktaOAuth2Configurer.java
- oauth2/src/main/java/com/okta/spring/boot/oauth/config/OktaOAuth2Properties.java
- oauth2/src/test/groovy/com/okta/spring/boot/oauth/AutoConfigConditionalTest.groovy
- pom.xml
* work around configuration processor issue spring-projects/spring-boot#17035
* Adjust AutoConfig tests to apply EnvironmentPostProcessor when context is loaded.
> Couple minor configuration tweaks to add Spring Boot 2.2 support

- examples/hosted-login-code-flow/pom.xml
- examples/redirect-code-flow/pom.xml
- examples/siw-jquery/pom.xml
- examples/webflux-resource-server/pom.xml
- pom.xml
Remove duplicate code in example pom files (otherwise the dep management section will override the new jackson version)
> Update Jackson to 2.9.9

- .travis.yml
> Update travis.yml to use openjdk8

- coverage/pom.xml
- examples/config-server/pom.xml
- examples/hosted-login-code-flow/pom.xml
- examples/pom.xml
- examples/redirect-code-flow/pom.xml
- examples/siw-jquery/pom.xml
- examples/webflux-resource-server/pom.xml
- integration-tests/oauth2-reactive/pom.xml
- integration-tests/oauth2-reactive/src/main/java/com/okta/spring/tests/oauth2/reactive/code/ReactiveRedirectCodeFlowApplication.java
- integration-tests/oauth2-reactive/src/test/resources/testRunner.yml
- integration-tests/oauth2/pom.xml
- integration-tests/oauth2/src/main/java/com/okta/spring/tests/oauth2/code/BasicRedirectCodeFlowApplication.java
- integration-tests/oauth2/src/test/resources/testRunner.yml
- oauth2/pom.xml
- oauth2/src/main/java/com/okta/spring/boot/oauth/OktaOAuth2AutoConfig.java
- oauth2/src/main/java/com/okta/spring/boot/oauth/OktaOAuth2Configurer.java
- oauth2/src/main/java/com/okta/spring/boot/oauth/ReactiveOktaOAuth2ServerHttpServerAutoConfig.java
- oauth2/src/main/java/com/okta/spring/boot/oauth/config/OktaOAuth2Properties.java
- oauth2/src/main/java/com/okta/spring/boot/oauth/env/OktaOAuth2PropertiesMappingEnvironmentPostProcessor.java
- oauth2/src/test/groovy/com/okta/spring/boot/oauth/AutoConfigConditionalTest.groovy
- oauth2/src/test/groovy/com/okta/spring/boot/oauth/HttpMock.groovy
- okta-spring-boot-starter/pom.xml
- pom.xml
- sdk/pom.xml
- src/findbugs/findbugs-exclude.xml
- src/owasp/owasp-suppression.xml
I have a bunch of Spring Sec 5.2 changes queued up, I'm going to start trickling them into the `spring-boot-2-2` branch.
NOTE: Integration tests have also been added to `okta-oidc-tck` (and are now run as part of this project)
> Support RP-Initiated logout

- README.md
The redirect URI that you need for Spring Boot it not documented. I think it should be.
> Add Web app instructions

- pom.xml
Update Spring Cloud and Okta SDK versions too
> Update Spring Boot version

- oauth2/src/main/java/com/okta/spring/boot/oauth/AuthoritiesProvider.java
- oauth2/src/main/java/com/okta/spring/boot/oauth/AuthorityProvidersConfig.java
- oauth2/src/main/java/com/okta/spring/boot/oauth/OktaOAuth2AutoConfig.java
- oauth2/src/main/java/com/okta/spring/boot/oauth/OktaOAuth2UserService.java
- oauth2/src/main/java/com/okta/spring/boot/oauth/OktaOidcUserService.java
- oauth2/src/main/java/com/okta/spring/boot/oauth/ReactiveOktaOAuth2AutoConfig.java
- oauth2/src/main/java/com/okta/spring/boot/oauth/ReactiveOktaOAuth2UserService.java
- oauth2/src/main/java/com/okta/spring/boot/oauth/ReactiveOktaOidcUserService.java
- oauth2/src/main/java/com/okta/spring/boot/oauth/UserUtil.java
- oauth2/src/test/groovy/com/okta/spring/boot/oauth/AuthorityProvidersConfigTest.groovy
- oauth2/src/test/groovy/com/okta/spring/boot/oauth/AutoConfigConditionalTest.groovy
Converted existing code to use this new interface (scopes and groups)
Fixes: #136
> Add new AuthoritiesProvider interface to adding custom GrantedAuthorities

- coverage/pom.xml
- examples/config-server/pom.xml
- examples/hosted-login-code-flow/pom.xml
- examples/pom.xml
- examples/redirect-code-flow/pom.xml
- examples/siw-jquery/pom.xml
- examples/webflux-resource-server/pom.xml
- integration-tests/oauth2-reactive/pom.xml
- integration-tests/oauth2/pom.xml
- oauth2/pom.xml
- okta-spring-boot-starter/pom.xml
- pom.xml
- sdk/pom.xml
> Updating version to 1.4.0

- README.md
> Update minimum Spring Boot version in readme

- README.md
https://github.com/okta/okta-spring-boot/issues/164
> Add okta.oauth2.postLogoutRedirectUri to README

- coverage/pom.xml
- examples/config-server/pom.xml
- examples/hosted-login-code-flow/pom.xml
- examples/pom.xml
- examples/redirect-code-flow/pom.xml
- examples/siw-jquery/pom.xml
- examples/webflux-resource-server/pom.xml
- integration-tests/oauth2-reactive/pom.xml
- integration-tests/oauth2/pom.xml
- oauth2/pom.xml
- oauth2/src/main/java/com/okta/spring/boot/oauth/OktaOAuth2AutoConfig.java
- oauth2/src/main/java/com/okta/spring/boot/oauth/ReactiveOktaOAuth2ServerHttpServerAutoConfig.java
- oauth2/src/test/groovy/com/okta/spring/boot/oauth/AutoConfigConditionalTest.groovy
- okta-spring-boot-starter/pom.xml
- pom.xml
- sdk/pom.xml
- sdk/src/main/java/com/okta/spring/boot/sdk/OktaSdkConfig.java
- sdk/src/main/java/com/okta/spring/boot/sdk/cache/SpringCache.java
- sdk/src/main/java/com/okta/spring/boot/sdk/cache/SpringCacheManager.java
- sdk/src/test/groovy/com/okta/spring/boot/sdk/OktaSdkConfigWithProxyTest.groovy
Fix kabob case issue
Bump version to v2 (the SDK contains breaking changes)
update spring versions
> Update to v2 of the Okta SDK

- README.md
[OKTA-323354](https://oktainc.atlassian.net/browse/OKTA-323354)
> Update README on how to add custom claims to JWT access token

- README.md
https://github.com/okta/okta-spring-boot/issues/188
> Update README with Proxy info

- README.md
https://github.com/okta/okta-spring-boot/issues/186
> Update Quickstart section in README

- README.md
https://github.com/okta/okta-spring-boot/issues/178
> Add Spring MVC sample to README

- integration-tests/oauth2-reactive/src/test/resources/testRunner.yml
- integration-tests/oauth2/src/main/java/com/okta/spring/tests/oauth2/jwt/BasicJwtResourceServerApplication.java
- integration-tests/oauth2/src/main/java/com/okta/spring/tests/oauth2/opaquetoken/BasicOpaqueTokenResourceServerApplication.java
- integration-tests/oauth2/src/test/groovy/com/okta/spring/tests/oauth2/jwt/ResourceServerJwtValidationIT.groovy
- integration-tests/oauth2/src/test/groovy/com/okta/spring/tests/oauth2/opaquetoken/ResourceServerOpaqueTokenValidationIT.groovy
- integration-tests/oauth2/src/test/resources/testRunner.yml
- oauth2/src/main/java/com/okta/spring/boot/oauth/OktaOAuth2ResourceServerAutoConfig.java
- oauth2/src/main/java/com/okta/spring/boot/oauth/TokenUtil.java
- oauth2/src/test/groovy/com/okta/spring/boot/oauth/TokenUtilTest.groovy
- pom.xml
**Note:** Travis build of this PR won't pass unless https://github.com/okta/okta-oidc-tck/pull/87 is merged and `okta-oidc-tck` version **0.5.7** is released.
> fix issue with authorities found while testing samples

- coverage/pom.xml
- examples/config-server/pom.xml
- examples/hosted-login-code-flow/pom.xml
- examples/pom.xml
- examples/redirect-code-flow/pom.xml
- examples/siw-jquery/pom.xml
- examples/webflux-resource-server/pom.xml
- integration-tests/oauth2-reactive/pom.xml
- integration-tests/oauth2/pom.xml
- oauth2/pom.xml
- okta-spring-boot-starter/pom.xml
- pom.xml
- sdk/pom.xml
Patch Release `v1.5.1` that fixes #218.
> Release 1.5.1

- oauth2/src/main/java/com/okta/spring/boot/oauth/env/OktaEnvironmentPostProcessorApplicationListener.java
- oauth2/src/main/java/com/okta/spring/boot/oauth/env/OktaOAuth2PropertiesMappingEnvironmentPostProcessor.java
- oauth2/src/main/resources/META-INF/spring.factories
- oauth2/src/test/groovy/com/okta/spring/boot/oauth/AutoConfigConditionalTest.groovy
- oauth2/src/test/groovy/com/okta/spring/boot/oauth/env/OktaEnvironmentPostProcessorApplicationListenerTest.groovy
https://github.com/okta/samples-java-spring/issues/77
> Improve exception message thrown in startup failure

- sdk/src/main/java/com/okta/spring/boot/sdk/OktaSdkConfig.java
- sdk/src/main/java/com/okta/spring/boot/sdk/env/OktaSdkPropertiesEnvironmentPostProcessor.java
- sdk/src/test/groovy/com/okta/spring/boot/sdk/OktaApiConditionsTest.groovy
- sdk/src/test/groovy/com/okta/spring/boot/sdk/env/OktaSdkPropertiesEnvironmentPostProcessorTest.groovy
> SDK Client fails to load if `orgUrl` is NOT set

- oauth2/src/main/java/com/okta/spring/boot/oauth/env/OktaOAuth2PropertiesMappingEnvironmentPostProcessor.java
- oauth2/src/test/groovy/com/okta/spring/boot/oauth/env/OktaOAuth2PropertiesMappingEnvironmentPostProcessorTest.groovy
Issue: https://github.com/okta/okta-spring-boot/issues/273
Jira ticket: https://oktainc.atlassian.net/browse/OKTA-383228
> Incorrect Authorize URL if root Org issuer is set

- coverage/pom.xml
- examples/config-server/pom.xml
- examples/hosted-login-code-flow/pom.xml
- examples/pom.xml
- examples/redirect-code-flow/pom.xml
- examples/siw-jquery/pom.xml
- examples/webflux-resource-server/pom.xml
- integration-tests/common-reactive/pom.xml
- integration-tests/common-servlet/pom.xml
- integration-tests/oauth2-reactive-spring/pom.xml
- integration-tests/oauth2-reactive/pom.xml
- integration-tests/oauth2-servlet-spring/pom.xml
- integration-tests/oauth2-servlet/pom.xml
- oauth2/pom.xml
- okta-spring-boot-starter/pom.xml
- pom.xml
- sdk/pom.xml
minor version bump to match the minor bump in Spring Boot
> Setting project version to 2.1.0

- coverage/pom.xml
- pom.xml
Related to https://github.com/okta/okta-spring-boot/pull/261.
> Removing orphaned/unused modules after splitting up integration tests

- oauth2/src/main/java/com/okta/spring/boot/oauth/OktaOAuth2AutoConfig.java
As learned with @joshlong and @bdemers on Twitch today.
> Change oidcUserService to use Qualifer bean

- README.md
- oauth2/src/main/java/com/okta/spring/boot/oauth/OktaOAuth2AutoConfig.java
- oauth2/src/main/java/com/okta/spring/boot/oauth/ReactiveOktaOAuth2ServerHttpServerAutoConfig.java
- oauth2/src/test/groovy/com/okta/spring/boot/oauth/AutoConfigConditionalTest.groovy
[OKTA-212902](https://oktainc.atlassian.net/browse/OKTA-212902)
> OKTA-212902: Add relative path support for `postLogoutRedirectUri`

- oauth2/src/main/java/com/okta/spring/boot/oauth/OktaOAuth2AutoConfig.java
See https://github.com/spring-projects-experimental/spring-native/releases/tag/0.8.3
> proxyBeanMethods = false not needed since Spring Native 0.8.3

- README.md
> User correct terminology in readme

- oauth2/pom.xml
Fix https://github.com/okta/okta-spring-boot/runs/4891969266?check_suite_focus=true
> set validation-api version in pom.xml

- integration-tests/common-reactive/src/main/java/com/okta/spring/tests/common/reactive/code/ReactiveRedirectCodeFlowApplication.java
- integration-tests/common-servlet/src/main/java/com/okta/spring/tests/common/servlet/code/BasicRedirectCodeFlowApplication.java
- integration-tests/common-servlet/src/test/groovy/com/okta/spring/tests/common/servlet/redirect/OidcRedirectLoginValidationIT.groovy
- integration-tests/oauth2-reactive-spring/pom.xml
- integration-tests/oauth2-reactive/pom.xml
- integration-tests/oauth2-servlet-spring/pom.xml
- integration-tests/oauth2-servlet/pom.xml
- oauth2/src/main/java/com/okta/spring/boot/oauth/Okta.java
- oauth2/src/main/java/com/okta/spring/boot/oauth/OktaOAuth2AutoConfig.java
- oauth2/src/main/java/com/okta/spring/boot/oauth/ReactiveOktaOAuth2AutoConfig.java
- Enable missing common ITs
- Enable PKCE by default for confidential clients
> pkce by default

- oauth2/pom.xml
- pom.xml
Related PR: https://github.com/okta/okta-oidc-tck/pull/169
> Fix build issues on Java 17

- oauth2/pom.xml
- oauth2/src/main/java/com/okta/spring/boot/oauth/env/OktaOAuth2PropertiesMappingEnvironmentPostProcessor.java
- oauth2/src/test/groovy/com/okta/spring/boot/oauth/AutoConfigConditionalTest.groovy
Fixes https://github.com/okta/okta-spring-boot/issues/530
> replace javax import with jakarta

- oauth2/src/main/java/com/okta/spring/boot/oauth/OktaOAuth2Configurer.java
> fix application startup failure (505)

- coverage/pom.xml
- examples/config-server/pom.xml
- examples/hosted-login-code-flow/pom.xml
- examples/pom.xml
- examples/redirect-code-flow/pom.xml
- examples/siw-jquery/pom.xml
- examples/webflux-resource-server/pom.xml
- integration-tests/common-reactive/pom.xml
- integration-tests/common-servlet/pom.xml
- integration-tests/oauth2-reactive-spring/pom.xml
- integration-tests/oauth2-reactive/pom.xml
- integration-tests/oauth2-servlet-spring/pom.xml
- integration-tests/oauth2-servlet/pom.xml
- oauth2/pom.xml
- oauth2/src/main/java/com/okta/spring/boot/oauth/OktaOAuth2Configurer.java
- okta-spring-boot-starter/pom.xml
- pom.xml
- sdk/pom.xml
- src/owasp/owasp-suppression.xml
Port the fix https://github.com/okta/okta-spring-boot/pull/540 into 2.1.6 release branch and prepare for patch release 2.1.7
> prep for 2.1.7 patch release

- examples/config-server/pom.xml
- oauth2/pom.xml
- pom.xml
- src/owasp/owasp-suppression.xml
- Bump Spring cloud and mockserver-netty deps
- Add CVE suppression and remove unnecessary deps from examples/config-server/pom.xml
> Bump Spring cloud and mockserver-netty version

- oauth2/src/main/java/com/okta/spring/boot/oauth/OktaOAuth2ResourceServerAutoConfig.java
> Fix issue with RestTemplate which unsets the proxy

- oauth2/src/main/java/com/okta/spring/boot/oauth/OktaOAuth2Configurer.java
- oauth2/src/main/java/com/okta/spring/boot/oauth/env/OIDCMetadata.java
- oauth2/src/main/java/com/okta/spring/boot/oauth/env/OktaOAuth2PropertiesMappingEnvironmentPostProcessor.java
- oauth2/src/test/groovy/com/okta/spring/boot/oauth/env/OktaOAuth2PropertiesMappingEnvironmentPostProcessorTest.groovy
Initial support for Auth0 hosted login fix https://github.com/okta/okta-spring-boot/issues/358
> Add auth0 support

- .circleci/config.yml
> Update Snyk Dep Scan Config

- oauth2/src/main/java/com/okta/spring/boot/oauth/OktaJwtAuthenticationConverter.java
- oauth2/src/main/java/com/okta/spring/boot/oauth/OktaOAuth2ResourceServerAutoConfig.java
- oauth2/src/main/java/com/okta/spring/boot/oauth/config/OktaOAuth2Properties.java
- oauth2/src/test/groovy/com/okta/spring/boot/oauth/OktaJwtAuthenticationConverterTest.groovy
Original contribution: https://github.com/okta/okta-spring-boot/pull/648
Thanks [andreasnaess](https://github.com/andreasnaess) for your contribution!
> OKTA-595963: Add ability to set authorities claim name from config

- oauth2/src/main/java/com/okta/spring/boot/oauth/BrowserFriendlyBearerTokenServerAuthenticationEntryPoint.java
- oauth2/src/main/java/com/okta/spring/boot/oauth/Okta.java
- oauth2/src/main/java/com/okta/spring/boot/oauth/OktaOAuth2Configurer.java
- oauth2/src/main/java/com/okta/spring/boot/oauth/env/OIDCMetadata.java
- oauth2/src/main/java/com/okta/spring/boot/oauth/env/OktaEnvironmentPostProcessorApplicationListener.java
- pom.xml
- Bumped okta-parent from 31 to 32
- Fixed PMD errors
> Bump `com.okta:okta-parent` from `31` to `32`

- oauth2/src/main/java/com/okta/spring/boot/oauth/OktaOAuth2Configurer.java
- oauth2/src/main/java/com/okta/spring/boot/oauth/ReactiveOktaOAuth2ResourceServerHttpServerAutoConfig.java
Original PR https://github.com/okta/okta-spring-boot/pull/752
> Fix usage of OktaJwtAuthenticationConverter to use constructor with props

- pom.xml
https://oktainc.atlassian.net/browse/OKTA-866716
> OKTA-866716 - Outdated Library - okta/okta-spring-boot@master - net.minidev:json-smart@2.5.1

- pom.xml
https://oktainc.atlassian.net/browse/OKTA-869328
> OKTA-869328 - Outdated Library - okta/okta-spring-boot@master - io.netty:netty-handler@4.1.116.Final

- pom.xml
https://oktainc.atlassian.net/browse/OKTA-899032
> OKTA-899032 - Outdated Library - okta/okta-spring-boot@master - org.springframework.security:spring-security-crypto@6.4.2

- examples/config-server/pom.xml
- examples/hosted-login-code-flow/pom.xml
- examples/redirect-code-flow/pom.xml
- examples/siw-jquery/pom.xml
- integration-tests/oauth2-servlet/pom.xml
- pom.xml
https://oktainc.atlassian.net/browse/OKTA-892003
> updating outdated org.apache.tomcat.embed:tomcat-embed-core dependencies
