okta/okta-spring-boot

.travis.yml, okta-spring-security-starter/pom.xml, src/ci/build.sh
* Use travis deploy provider to deploy javadocs
* Generate the jacoco XML report for use with codecov
=> Cleanup CI build

integration-tests/oauth2/pom.xml, oauth2/src/main/java/com/okta/spring/oauth/ConfigurableAccessTokenConverter.java, oauth2/src/main/java/com/okta/spring/oauth/OktaTokenServicesConfig.java, oauth2/src/test/groovy/com/okta/spring/oauth/ConfigurableAccessTokenConverterTest.groovy
Spring Security does this when validating tokens remotely, so we need to set the user details when validating locally.
=> User details claims

oauth2/src/main/java/com/okta/spring/oauth/OktaPropertiesMappingEnvironmentPostProcessor.java, oauth2/src/main/java/com/okta/spring/oauth/OktaTokenServicesConfig.java, oauth2/src/main/java/com/okta/spring/oauth/RemappedPropertySource.java, oauth2/src/main/java/com/okta/spring/oauth/discovery/DiscoveryPropertySource.java, oauth2/src/main/resources/META-INF/spring.factories, oauth2/src/test/groovy/com/okta/spring/oauth/discovery/DiscoveryPropertySourceTest.groovy, oauth2/src/test/groovy/com/okta/spring/oauth/discovery/OidcDiscoveryClientTest.groovy, oauth2/src/test/groovy/com/okta/spring/oauth/implicit/ResourceServerConfigTest.groovy
Now they work with spring-cloud-config!
Fixes: #26
This could sill use a few UTs in the `discovery` package, but any thoughts?  It feels like should be an easier way to do all of this.  Both the aliasing of the config properties and the injecting of the discovery metadata into the _standard_ spring properties.
There are no tests currently for spring-cloud-config, but I've manually verified that lazy loading the config properties allows for spring-cloud-config to be used to configure the `okta.*` props.
=> Lazy loading properties configured via OIDC discovery and OktaPropertiesMappingEnvironmentPostProcessor

integration-tests/oauth2/src/main/java/com/okta/spring/tests/oauth2/code/BasicRedirectCodeFlowApplication.java, okta-spring-boot-starter/pom.xml
I'm guessing Maven was overriding the 'optional' declaration because those dependencies are NOT optional in one of the transitive dependencies.
Added annotation to BasicRedirectCodeFlowApplication to fail the test if the SDK is on the classpath
=> Make the SDK truly optional

oauth2/src/main/java/com/okta/spring/oauth/OktaPropertiesMappingEnvironmentPostProcessor.java, oauth2/src/main/java/com/okta/spring/oauth/RemappedPropertySource.java, oauth2/src/test/groovy/com/okta/spring/oauth/OktaPropertiesMappingEnvironmentPostProcessorTest.groovy
=> Allow okta.client.org-url to be parsed from okta.oauth2.issuer with Spring Boot 2

oauth2/src/main/java/com/okta/spring/oauth/code/OktaOAuthCodeFlowConfiguration.java, oauth2/src/main/java/com/okta/spring/oauth/code/OktaOAuthCodeFlowCustomConfiguration.java, oauth2/src/main/java/com/okta/spring/oauth/code/OktaOAuthCodeFlowDefaultConfiguration.java, oauth2/src/main/resources/META-INF/spring.factories, oauth2/src/test/groovy/com/okta/spring/oauth/code/MockCustomSsoCodeFlowApp.groovy, oauth2/src/test/groovy/com/okta/spring/oauth/code/OktaOAuthCodeFlowCustomConfigurationTest.groovy, oauth2/src/test/groovy/com/okta/spring/oauth/code/OktaOAuthCodeFlowDefaultConfigurationTest.groovy
Fixes: #29 
NOTE: the `custom` version is loaded when you annotate a `WebSecurityConfigurerAdapter` with `@EnableOAuth2Sso`
=> Breaking up OktaOAuthCodeFlowConfiguration to support Spring's OAuth2SsoCustomConfiguration

oauth2/src/main/java/com/okta/spring/oauth/code/CodeFlowAudienceValidatingTokenServices.java, oauth2/src/main/java/com/okta/spring/oauth/code/OktaOAuthCodeFlowConfiguration.java, oauth2/src/main/java/com/okta/spring/oauth/implicit/ImplicitAudienceValidatingTokenServices.java, oauth2/src/main/java/com/okta/spring/oauth/implicit/ResourceServerConfig.java
I could only reproduce an issue when:
1. devtools on the classpath
2. spring-boot-starter-data-jpa (and an impl) on the classpath
3. okta-spring-boot-starter was NOT available in the same Intellij project
The fix was ultimately making the TokenService class public
Fixes #40
=> Fix error starting applications when dev tools is on the classpath

.travis.yml, pom.xml
- Updated parent, plugin, and library versions to support Java 11
- minor travis.yml formatting (to match other projects)
=> Run CI with JDK 8 and 11

README.md
`@AuthenticationPrincipal OidcUser oidcUser` use instead of `Principal`, which makes it more clear how to get other OIDC info from the principal
Fixes: #76
=> Updates Web example in readme to use OidcUser

integration-tests/oauth2-reactive/src/main/java/com/okta/spring/tests/oauth2/reactive/code/ReactiveRedirectCodeFlowApplication.java, integration-tests/oauth2-reactive/src/test/resources/testRunner.yml, integration-tests/oauth2/src/main/java/com/okta/spring/tests/oauth2/code/BasicRedirectCodeFlowApplication.java, integration-tests/oauth2/src/test/resources/testRunner.yml, oauth2/src/main/java/com/okta/spring/boot/oauth/ConditionalOnOktaClientProperties.java, oauth2/src/main/java/com/okta/spring/boot/oauth/OktaOAuth2Configurer.java, oauth2/src/main/java/com/okta/spring/boot/oauth/UserUtil.java, oauth2/src/test/groovy/com/okta/spring/boot/oauth/AutoConfigConditionalTest.groovy, pom.xml
ITs to support PCKE have already been added to okta-oidc-tck (and will run automatically now that it is configured in testRunner.yml)
TL;DR: client-secret is no longer required
=> Add PKCE support

oauth2/src/main/java/com/okta/spring/boot/oauth/OktaOAuth2AutoConfig.java, oauth2/src/main/java/com/okta/spring/boot/oauth/OktaOAuth2Configurer.java, oauth2/src/main/java/com/okta/spring/boot/oauth/ReactiveOktaOAuth2AutoConfig.java, oauth2/src/test/groovy/com/okta/spring/boot/oauth/AutoConfigConditionalTest.groovy
Previously we used an AbstractHttpConfigurer to set the Okta implementation of the OAuth2UserService (and oidc user service)
This made replacing Okta impl impossible to replace due to how/when those impls were configured.
Now they loaded automatically.
Fixes: #136
=> Define and use OAuth2UserService beans

README.md
In older versions, this property was resolved automatically but caused a few edge cases.
Users can reduce duplication by doing something like:
```properties
okta.client.orgUrl=https://dev-123456.okta.com
okta.oauth2.issuer=${okta.client.orgUrl}/oauth2/default
```
=> Add note in readme about the orgUrl property

oauth2/src/main/java/com/okta/spring/boot/oauth/OktaOAuth2ResourceServerAutoConfig.java
**NOTE:** This should be retargeted to v2 once `add_opaque_token_validation_support` is merged in.
I'm targeting `add_opaque_token_validation_support` to avoid merge conflicts
=> Removes deprecated code that creates a JwtDecoder

oauth2/src/main/java/com/okta/spring/boot/oauth/env/OktaOAuth2PropertiesMappingEnvironmentPostProcessor.java, oauth2/src/test/groovy/com/okta/spring/boot/oauth/env/OktaOAuth2PropertiesMappingEnvironmentPostProcessorTest.groovy
Updated conditional property logic to take a list of strings, this ensures that BOTH issuer and secret are set before remapping properties
=> Ensuring the Okta Env Post Processor only sets valid properties

integration-tests/oauth2-reactive/pom.xml, integration-tests/oauth2-reactive/src/test/resources/testRunner.yml, integration-tests/oauth2/pom.xml, integration-tests/oauth2/src/test/resources/testRunner.yml, oauth2/src/main/java/com/okta/spring/boot/oauth/OktaOAuth2AutoConfig.java, oauth2/src/main/java/com/okta/spring/boot/oauth/OktaOAuth2Configurer.java, oauth2/src/main/java/com/okta/spring/boot/oauth/OktaOAuth2ResourceServerAutoConfig.java, oauth2/src/main/java/com/okta/spring/boot/oauth/ReactiveOktaOAuth2AutoConfig.java, oauth2/src/main/java/com/okta/spring/boot/oauth/config/OktaOAuth2Properties.java, oauth2/src/main/java/com/okta/spring/boot/oauth/env/OktaOAuth2PropertiesMappingEnvironmentPostProcessor.java, oauth2/src/test/groovy/com/okta/spring/boot/oauth/AutoConfigConditionalTest.groovy, pom.xml, src/owasp/owasp-suppression.xml
A few things change in Spring Security 5.4 (used by Spring Boot 2.4)
1. The default WebSecurityAdapter (or equivalent, now configures a "login" or a "resource server", not both by default
- this change restores that functionality
2. PKCE for unauthenticated clients looks to be NOT configured by default 
- though I might be missing something there, open question to the Spring Security team on Gitter
3. Default OAuth scopes are NO longer set by Spring Security
- this change restores that functionality, setting them to the previous default of: `openid, profile, email`
4. It's now easier to set the JWT converter, you can just inject it!
5. Minor test changes (we have tests that poke at the internals of spring sec, these often need to change when implementation details change)
=> Update to Spring Boot 2.4.0

coverage/pom.xml, examples/config-server/pom.xml, examples/hosted-login-code-flow/pom.xml, examples/pom.xml, examples/redirect-code-flow/pom.xml, examples/siw-jquery/pom.xml, examples/webflux-resource-server/pom.xml, integration-tests/oauth2-reactive/pom.xml, integration-tests/oauth2/pom.xml, oauth2/pom.xml, okta-spring-boot-starter/pom.xml, pom.xml, sdk/pom.xml
Set version to `1.5.0-SNAPSHOT` and thereby prep for minor version `1.5.0` release (current release version is the wild is 1.4.0).
` mvn versions:set -DnewVersion=1.5.0-SNAPSHOT` was run to achieve this.
Also bumped up `okta-oidc-tck` version from `0.5.6` to `0.5.7`.
=> Prep for minor version release 1.5.0

integration-tests/oauth2-reactive/src/test/resources/testRunner.yml, integration-tests/oauth2/src/test/resources/testRunner.yml, oauth2/src/main/java/com/okta/spring/boot/oauth/OktaOAuth2AutoConfig.java, oauth2/src/main/java/com/okta/spring/boot/oauth/OktaOAuth2ResourceServerAutoConfig.java, oauth2/src/test/groovy/com/okta/spring/boot/oauth/AutoConfigConditionalTest.groovy
The previous release had the OktaJwtAuthenticationCoverter nested in the OktaOAuthAutoConfig, which adds a conditional on the `client-id` property which is NOT needed for the JWT converter
This change moves this converter to its correct location in the OktaResourceServerAuthConfig, UTs not check for this bean, and the corresponding ITs are now run WITHOUT the client-id property
Fixes: #218
=> Move JwtAuthenticationCoverter to the ResourceServerAuthConfig class

pom.xml, src/owasp/owasp-suppression.xml
Address below CVEs:
1. ` jackson-databind-2.10.0.jar (pkg:maven/com.fasterxml.jackson.core/jackson-databind@2.10.0, cpe:2.3:a:fasterxml:jackson:2.10.0:*:*:*:*:*:*:*, cpe:2.3:a:fasterxml:jackson-databind:2.10.0:*:*:*:*:*:*:*) : CVE-2020-25649`
2. `tomcat-embed-core-9.0.39.jar (pkg:maven/org.apache.tomcat.embed/tomcat-embed-core@9.0.39, cpe:2.3:a:apache:tomcat:9.0.39:*:*:*:*:*:*:*, cpe:2.3:a:apache_software_foundation:tomcat:9.0.39:*:*:*:*:*:*:*, cpe:2.3:a:apache_tomcat:apache_tomcat:9.0.39:*:*:*:*:*:*:*) : CVE-2020-17527`
=> address cve

pom.xml
Revert https://github.com/okta/okta-spring-boot/commit/5f1fd863aad55d4d07449c4dfe5afe656335b691
The upgrade done earlier brought in a lot of vulnerabilities and we do not want to introduce them into the project at this point (we can wait till a newer version of spring cloud is released with all those vulnerabilities resolved).
=> Revert spring-cloud upgrade introduced by snyk

src/owasp/owasp-suppression.xml
Fix CVE error false positive reported by `mvn dependency-check:check`
```
[ERROR] Failed to execute goal org.owasp:dependency-check-maven:6.1.0:aggregate (default-cli) on project okta-spring-boot-parent:
[ERROR]
[ERROR] One or more dependencies were identified with vulnerabilities:
[ERROR]
[ERROR] spring-security-rsa-1.0.9.RELEASE.jar: CVE-2011-2732, CVE-2011-2731, CVE-2012-5055
[ERROR]
[ERROR] See the dependency-check report for more details.
[ERROR]
[ERROR]
[ERROR] -> [Help 1]
```
=> fix cve analysis false positives

README.md
having the 0 hardcoded in 2.x.0 is kind of confusing when current version is actually 2.0.1
=> clean Spring Boot Version Compatibility

integration-tests/oauth2-reactive-spring/src/test/resources/testRunner.yml, integration-tests/oauth2-servlet-spring/src/test/resources/testRunner.yml, oauth2/src/main/java/com/okta/spring/boot/oauth/OktaOAuth2Configurer.java, oauth2/src/main/java/com/okta/spring/boot/oauth/env/OktaOAuth2PropertiesMappingEnvironmentPostProcessor.java, oauth2/src/test/groovy/com/okta/spring/boot/oauth/AutoConfigConditionalTest.groovy, pom.xml
Fixes: #280
From commits:
Update to Spring Boot 2.5
With 2.5 a JwtDecoder bean is now initialized when `spring.security.oauth2.resourceserver.jwt.issuer-uri` is set.  There were a few invalid test assumptions that were setting this property (likely a copypasta eror)
For example the OAuth Code Flow ITs check to make sure requests to the /keys endpoint is NOT called (not needed for non OIDC or jwt resource server usage).
Another fix with a fragile test which detects the internal configuration of Spring Security.
OktaOAuth2Configurer had an unused else block, which caused a problem with 2.5 when a resource server was not configured.
=> Testing build with Spring Boot 2.5.1

src/owasp/owasp-suppression.xml
This CVE was fixed in 6.1.5 per: https://in.relation.to/2020/05/07/hibernate-validator-615-6020-released/
And the release notes for 6.2.0 make reference to that post/fix: https://in.relation.to/2021/01/06/hibernate-validator-700-62-final-released/
=> Add exclusion fro hibernate-validator in owasp-suppression

pom.xml
- Fixes #308 
- Remove Jackson version override in pom
- Update to Java parent v21
=> Remove Jackson dep version override in pom

README.md
Depends on https://github.com/okta/okta-spring-boot/pull/311.
=> Add note about Spring Native to README

pom.xml
https://github.com/okta/okta-spring-boot/runs/4848080929?check_suite_focus=true
https://github.com/okta/okta-spring-boot/runs/4848080983?check_suite_focus=true
There seems to be a compatibility issue running ITs with TestNG `7.5`:
```
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: There was an error in the forked process
[ERROR] org/testng/xml/XmlSuite.setParallel(Ljava/lang/String;)V (loaded from file:/Users/<blahblah>/.m2/repository/org/testng/testng/7.5/testng-7.5.jar by sun.misc.Launcher$AppClassLoader@8399a5c7) called from class org.apache.maven.surefire.testng.conf.TestNGMapConfigurator (loaded from file:/Users/<blahblah>/.m2/repository/org/apache/maven/surefire/surefire-testng/2.22.2/surefire-testng-2.22.2.jar by sun.misc.Launcher$AppClassLoader@8399a5c7). …
```
=> Downgraded testng to 7.3.0 to fix compatibility issue with 7.5

oauth2/src/main/java/com/okta/spring/boot/oauth/OktaOAuth2Configurer.java
Obvious Fix：
Fix the occurrence of NoUniqueBeanDefinitionException when there are multiple `org.springframework.core.env.Environment` instance bean during `OktaOAuth2Configurer.init()` to call `context.getBean(Class<T> requiredType)` where only class type as needed. More details see #445
=> Obvious Fix the NoUniqueBeanDefinitionException when get Environment bean

oauth2/src/main/java/com/okta/spring/boot/oauth/OktaJwtAuthenticationConverter.java, oauth2/src/main/java/com/okta/spring/boot/oauth/OktaOAuth2ResourceServerAutoConfig.java, oauth2/src/test/groovy/com/okta/spring/boot/oauth/OktaJwtAuthenticationConverterTest.groovy
The previous usage of `extractAuthorities()`, is deprecated and was removed in Spring Boot v3 (Spring Sec v6)
=> Update to newer JwtGrantedAuthoritiesConverter API

oauth2/src/main/java/com/okta/spring/boot/oauth/OktaOAuth2AutoConfig.java, oauth2/src/main/java/com/okta/spring/boot/oauth/OktaOAuth2ResourceServerAutoConfig.java, oauth2/src/main/java/com/okta/spring/boot/oauth/ReactiveOktaOAuth2AutoConfig.java, oauth2/src/main/java/com/okta/spring/boot/oauth/ReactiveOktaOAuth2ResourceServerAutoConfig.java, oauth2/src/main/java/com/okta/spring/boot/oauth/ReactiveOktaOAuth2ResourceServerHttpServerAutoConfig.java, oauth2/src/main/java/com/okta/spring/boot/oauth/ReactiveOktaOAuth2ServerHttpServerAutoConfig.java, oauth2/src/main/resources/META-INF/spring.factories, oauth2/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports, sdk/src/main/java/com/okta/spring/boot/sdk/OktaSdkConfig.java, sdk/src/main/resources/META-INF/spring.factories, sdk/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
Support for auto config classes in spring.factories has been removed in v3. AutoConfiguration.imports must be used now (and can be used after 2.7)
See: https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.7-Release-Notes#new-autoconfiguration-annotation
=> Migrate spring auto config away from spring.factories

oauth2/pom.xml
spring-boot-dependencies uses this dep
(NOTE: this will work with both javax and jakarta packages depending on the version of spring used)
=> Use Jakarta package for servlet-api

pom.xml
Latest plugin version will automatically be picked up from parent project (https://github.com/okta/okta-java-parent/blob/master/pom.xml#L153).
=> Remove version from `dependency-check-maven` plugin

oauth2/src/main/java/com/okta/spring/boot/oauth/http/Auth0ClientRequestInterceptor.java, oauth2/src/test/groovy/com/okta/spring/boot/oauth/http/Auth0ClientRequestInterceptorTest.groovy
These headers were missed originally in https://github.com/okta/okta-spring-boot/pull/586.
=> Add missing license headers

pom.xml, src/owasp/owasp-suppression.xml
- Bump `ch.qos.logback:logback-classic` from 1.4.11 to 1.4.13
- Add `ch.qos.logback:logback-core` v1.4.13 to fix cve
- Cleanup CVE suppression file and add new entries.
=> Cleanup CVE suppressions and deps

pom.xml
OKTA-699955
https://mvnrepository.com/artifact/org.springframework.security/spring-security-oauth2-jose/6.2.3 pulls in an older version of nimbus-jose-jwt, so we are enforcing a newer `9.37.3` with this PR.
=> Enforce `nimus-jose-jwt` `9.37.3` in pom.xml

pom.xml
This PR updates the org.springframework.security dependency from version 6.4.4 to 6.4.6 to remediate multiple vulnerabilities identified by Snyk.
=> Upgrading org.springframework.security to v6.4.6 

pom.xml
This PR resolves two high-severity vulnerabilities identified by Snyk in `tomcat-embed-core@11.0.8`:
- **CVE-2025-52520** (Integer Overflow)
- **CVE-2025-53506** (Resource Allocation Without Limits)
The fix is applied by upgrading to `tomcat-embed-core@11.0.9`, which includes patches for both CVEs.
=> Upgrade tomcat-embed-core to 11.0.9 to fix CVE-2025-52520 and CVE-2025-53506
